services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: santicode
      POSTGRES_PASSWORD: santicode
      POSTGRES_DB: nearty_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  postgres-data:
